fix: Comment out organizationId field in clients schema - column doesn't exist in database
Error: Unknown column 'organization_id' in 'field list'
This field was defined in Drizzle schema but doesn't exist in the actual database table.